USE [master]
GO

/****** Object:  Database [MAQSPerform]    Script Date: 1/25/2017 9:35:47 AM ******/
CREATE DATABASE [MAQSPerform]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MAQSPerform', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MAQSPerform.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MAQSPerform_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MAQSPerform_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MAQSPerform] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MAQSPerform].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MAQSPerform] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MAQSPerform] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MAQSPerform] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MAQSPerform] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MAQSPerform] SET ARITHABORT OFF 
GO

ALTER DATABASE [MAQSPerform] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MAQSPerform] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MAQSPerform] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MAQSPerform] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MAQSPerform] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MAQSPerform] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MAQSPerform] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MAQSPerform] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MAQSPerform] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MAQSPerform] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MAQSPerform] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MAQSPerform] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MAQSPerform] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MAQSPerform] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MAQSPerform] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MAQSPerform] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MAQSPerform] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MAQSPerform] SET RECOVERY FULL 
GO

ALTER DATABASE [MAQSPerform] SET  MULTI_USER 
GO

ALTER DATABASE [MAQSPerform] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MAQSPerform] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MAQSPerform] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MAQSPerform] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MAQSPerform] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MAQSPerform] SET  READ_WRITE 
GO


